config/routes.rb
Rails.application.routes.draw do
  get 'patients/index'
  get 'patients/show'
  get 'patients/new'
  get 'doctors/index'
  get 'doctors/show'
  get 'doctors/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root 'doctors#index'

resources :patients
resources :doctors

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
end

app/models/doctor.rb
class Doctor < ApplicationRecord
has_many :appointments
has_many :patients, through: :appointments

end

app/models/patient.rb
class Patient < ApplicationRecord
has_many :appointments
has_many :doctors, through: :appointments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :destroy]

  def index
    @doctor = Doctor.all
  end

  def show
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @user = Doctor.new(doctor_params)

    if @doctor.save
      redirect_to @doctor
    else
      render :new
    end
  end

  def destroy
    @doctor.destroy
    redirect_to doctors_path
  end

  private
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    def doctor_params
      params.require(:doctor).permit(:Name, :specialty)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_user, only: [:show, :destroy]

  def index
    @patients = Patient.all
  end

  def show
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)

    if @patient.save
      redirect_to @patient
    else
      render :new
    end
  end

  def destroy
    @patient.destroy
    redirect_to patients_path
  end

  private
    def set_patient
      @patient = Patient.find(params[:id])
    end

    def patient_params
      params.require(:patient).permit(:name, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/doctors/index.html.erb
<h1>Doctors</h1>
<%= link_to 'Add Doctor', new_doctor_path %>
<hr />
<h2><%= @doctor.length <= 0 ? "No Doctors" : "" %></h2> 
<ul>
  <% @doctor.each do |doctor| %>
    <li>
      <%= link_to doctor.name, doctor %>
    </li>
  <% end %>
</ul>

app/views/doctors/new.html.erb
<h1>Add Doctor</h1>
<%= form_with(model: @doctor, local: true, class: "ui form" ) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Doctor Name" %>
  </div>
  <%= f.submit nil, class: "ui blue button inverted" %>
<% end %>

app/views/doctors/show.html.erb
<h1>Doctors#show</h1>
<p>Find me in app/views/doctors/show.html.erb</p>

app/views/layouts/_navbar.html.erb
<div class="ui four item menu">
<%= link_to 'Doctors', doctors_path, class: "item"%>
<%= link_to 'Add Doctor', new_doctor_path, class: "item"%>
<%= link_to 'Patients', patients_path, class: "item"%>
<%= link_to 'Add Patient', new_patient_path, class: "item"%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoctorTime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <div class="ui container">
    <%= yield %>
  </body>
</html>

app/views/patients/index.html.erb
<h1>Patients#index</h1>
<p>Find me in app/views/patients/index.html.erb</p>

app/views/patients/new.html.erb
<h1>Patients#new</h1>
<p>Find me in app/views/patients/new.html.erb</p>

app/views/patients/show.html.erb
<h1>Patients#show</h1>
<p>Find me in app/views/patients/show.html.erb</p>